# test login 
POST http://localhost:8080/auth/login 
Content-Type: application/json 

{
    "email": "bomscoob@git.com",
    "password": "12346578"
}
###

# get profile
GET http://localhost:8080/users/me
Set-Cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJib21zY29vYiIsImVtYWlsIjoiYm9tc2Nvb2JAZ2l0LmNvbSIsImlhdCI6MTc1ODgwNzE3OSwiZXhwIjoxNzU4ODA4MDc5LCJpc3MiOiJlY2hvcG9zdCJ9.O4fKM0AYvTiiA5vRdZxEswOtrrc_3dJmavS_mh9hPUg; Path=/; HttpOnly,refresh_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJib21zY29vYiIsImVtYWlsIjoiYm9tc2Nvb2JAZ2l0LmNvbSIsImlhdCI6MTc1ODgwNzE3OSwiZXhwIjoxNzU4ODkzNTc5LCJpc3MiOiJlY2hvcG9zdCJ9.IhNO5qspYZf79rVfBgH1rgL-YkkT4Hhe90-J5802LDk; Path=/; HttpOnly